name: CORS Test
on: [push]
jobs:
  Test-CORS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - run: chmod +x ${{ github.workspace }}/scripts/corstest.sh
      - run: chmod +x ${{ github.workspace }}/scripts/test-feed-data.sh
      - run: bash ${{ github.workspace }}/scripts/corstest.sh